In [1]:
import numpy as np
from scipy import stats

### 1. Класичний та імовірнисний методи головних компонент. Методи отримання головних компонентів.
PCA can be defined as a set of methods which goal is to build an orthogonal basis of "best fitting" lines which minimize the average squared distance from a point to the line. 

* Classical PCA: Suppose we want to find an orthogonal set of 𝐿 linear basis vectors 𝐰_𝑗∈ℝ^𝐷, and the corresponding scores 𝐳_𝑖∈ℝ^𝐿, such that we minimize the average reconstruction error 𝐽(𝐖, 𝐙)=1/𝑁 ∑_(𝑖=1)^𝑁▒‖𝐱_𝑖−𝐱 ̂_𝑖 ‖^2 <br>
where 𝐱 ̂_𝑖=𝐖𝐳_𝑖, subject to the constrain that 𝐖 is orthonormal. Equivalently, we can write this objective as follow: $𝐽(𝐖, 𝐙)=〖‖𝐗−𝐖𝐙^𝑇 ‖_𝐹〗^2$
where 𝐙 is an 𝑁×𝐿 matrix with the 𝐳_𝑖 in its rows, and $||A||_F$ is the Frobenius norm of matrix 𝐀, defined by $‖𝐀‖_𝐹=√(∑_(𝑖=1)^𝑚▒∑_(𝑗=1)^𝑛▒〖𝑎_𝑖𝑗〗^2 )=√(𝑡𝑟 [𝐀^𝑇 𝐀] )=‖𝐀(:)‖_2$

The optimal solution is obtained by setting 𝐖 ̂=𝐕_𝐿, where 𝐕_𝐿 contains the 𝐿 eigenvectors with the largest eigenvalues of empirical covariance matrix, 𝚺 ̂=1/𝑁 ∑_(𝑖=1)^𝑁▒〖𝐱_𝑖 〖𝐱_𝑖〗^𝑇 〗 (we assume the 𝐱_𝑖 have zeros mean, for notation simplicity). Furthermore, the optimal low-dimensional encoding of data is given by 𝐳 ̂_𝑖=𝐖^𝑇 𝐱_𝑖, which is an orthogonal projection of the data onto the column space spanned by the eigenvectors.


* Probabilistic PCA: Consider a factor analysis model in which 𝚿=$\sigma^2I$ . The observed data log likelihood is given by $ log⁡[𝑝(𝐗|𝐖,𝜎^2 )]=(−𝑁/2)  ln⁡[𝐂]−1/2 \sum_{i=1}^N[〖𝐱_𝑖〗^𝑇 𝐂^(−1) 𝐱_𝑖 ]=(−𝑁/2)  ln⁡[𝐂]+tr[C^{-1} \sum] $

where 𝐂=𝐖𝐖^𝑇+𝜎^2 𝐈 and 𝐒=1/𝑁 ∑_(𝑖=1)^𝑁▒〖𝐱_𝑖 〖𝐱_𝑖〗^𝑇 〗=1/𝑁 𝐗^𝑇 𝐗 (we are assuming centered data, for notational simplicity). The maxima of the log-likelihood are given by 𝐖 ̂=𝐕(𝚲−𝜎^2 𝐈)^(1/2) 𝐑, where 𝐑 is an arbitrary 𝐿×𝐿 orthogonal matrix, 𝐕 is the 𝐷×𝐿 matrix whose columns are the first 𝐿 eigenvectors of the 𝐒, and 𝚲 is the corresponding diagonal matrix of eigenvalues.

the MLE of the noise variance s given by $\sigma^2=1/(D-L) \sum_{𝑗=𝐿+1}^D\lambda_j $

* PCA may also be solved via an SVD composition: any real NxD matrix X can be decomposed as $X_{NxD}=U_{NxN}* S_{NxD} * V_{DxD}^T$, where $U$ and $V$ are matrices with orthonormal columns, S - matrix of zeros, containing $r = min(N,D)$ singular values $\sigma_i>0$ on the main diagonal. Columns of U(V) are left(right) singular vectors

* PCA may be solved via EM-algorithm, with: <br>E-step: 𝐙 ̃=(𝐖^𝑇 𝐖)^(−1) 𝐖^𝑇 𝐗 <br>M-step: $W =XZ^T(ZZ^T)^-1 $, where $Z_{LxN}$ stands for a matrix storing the posterior means  along its columns; X~=X^T stores the original data along its columns

Some advantages of EM-algo:
   *  can be faster
   *  can handle missing data in a simple way

### 2. Метод незалежних компонент. Критерії незалежності компонентів.
ICA(Independent Component Analysis ) - method to separate multivariate sygnal into additive subcomponents without any previous "knowledge" about a source of sygnals; special case of blind source separation.
We assume that every subcomponent is a non-Gaussian signal and that all of them are statistically independent from each other

Criterias to estimate ICA params:
* Maximum likelihood estimation: $$NLL(V) = \sum_{j=1}^L E(G_j(z_j) \to\min$$
where $V=W^-1$ - recognition weights; $z_j≜[𝐯_𝑗]^𝑇𝐱$ and $𝐺_𝑗(𝑧)≜(−log⁡[𝑝_𝑗 (𝑧)] )$

* Maximizing non-Gaussianity – kurtosis or neg-entropy:$$negentropy(z) ≜ H[N(\mu,\sigma^2)]-H[z] $$
    
* Minimizing mutual information: $$I(z)≜𝕂𝕃[𝑝(𝐳)||\prod_j 𝑝(𝑧_𝑗 ) ]=\sum_j H[z_j] -H[z]$$
 


### 3. Застосування марківських моделей в задачах моделювання природних мов.
Можемо змоделювати речення у вигляді $P(x_1...x_t) = p(x1)p(x2|x1)p(x3|x1, x2) ... p(xt|x1 ... xt-1)$. Нам потрібно знайти найбільш ймовірну послідовність тегів за даного речення. $у = argmax P(y|x) = argmax p(x, y)$ де $P(x, y) = P(x|y)P(y) = Product from t=1 to T P(x_t|y_t)P(y_t|y_t-1)$ за умови Марківського припущення $p(y) = product from t=1 to T P(y_t|y_t-1)$

### 4. Умови існування стаціонарного розподілу для марківських моделей.

Мають виконуватися 2 умови:<br>

* Theorem: Every irreducible (singly connected), aperiodic finite state Markov chain has a limiting distribution, which is equal to pi, its unique stationary distribution.(Кожний непривідний аперіодичний ланцюг Маркова з кінцевою к-тю станів має обмежуючий розподіл,що співпадає з деяким розподілом pi , його єдиним стац. розподілом)<br>
* Theorem: Every irreducible (singly connected), ergodic Markov chain has a limiting distribution, which is equal to pi, its unique stationary distribution.<br>


### 5. Методи прийняття рішень (inference) з використанням прихованих марківських моделей.
L5, slide 15<br>
Фільтрування(filtering), згладжування з фіксованим лагом(fixed lag smoothing), передбачення(prediction),
оцінка апостеріорного максимуму(MAP estimation), 'Probability of the evidence'.


### 6. Робастна та гребнева (ridge) регресія. Порівняння з лінійною регресією.



### 7. Виведення основного рівняння лінійної регресії.



### 8. Поняття ядерних функцій. Вимоги до ядерних функцій (теорема Мерсера).
Ядерна функція - дійснозначна функція від двох змінних. Зазвичай функція є симетричною та невідємною, отже може бути інтерпретованою як міра схожості, але не завжди.
Теорема Мерсера: якщо матриця Грама є додатньо визначеню, ми можемо порахувати розклад власних векторів як $K = U^{T} * \lambda * U $ де $\lambda$ діагональна матриця власних невідємних чисел. Розглядаючи елементи матриці K:
     $k_{i,j} = (\lambda^{1/2} * U[:, i]) ^{T} * (\lambda^{1/2} * U[:, j])$ Можемо переписати $k_{i,j} = \phi(x_i)^{T} \phi(x_j)$. Якщо ядерна функція належить до классу Мерсера,тоді існує функція $\phi$ така, що: $k(x, x') = \phi(x)^{T}\phi(x')$

### 9. Відмінності лінійної та логістичної регресії з точки зору вирішеня задачі класифікації.
1. Відмінності лінійної та логістичної регресії з точки зору вирішеня задачі класифікації.
* Логістична регресія дає на вивід ймовірності (від 0 до 1), лінійна регресія - дійсні числа. 
* У випадку бінарної класифікації для логістичної регресії маємо відносити новий об'єкт до класу 0, якщо вивід моделі <0.5, інакше відносимо об'єкт до класу 1.
* Для лінійної регресії маємо спершу віднайти значення (max-min)/2 (або можливо інший decision boundary), та потім віднести об'єкт до відповідного класу.
* Загалом обидва методи відносяться до лінійних класифікаторів та є досить схожими.
* Деякі переваги логістичної регресії:
    *	LR models are easy to extend to multi-class classification;
    *	LR model can be easily be extended to handle non-linear decision boundaries by using kernels or by learning features from data.

### 10. Метод опорних векторів (Support Vector Machine, SVM). Відмінності від інших методів класифікації даних.

Метод опорних векторів (англ. SVM, support vector machine) — набір алгоритмів машинного навчання з учителем,
що використовуються для задач класифікації та регресійного аналізу. 
Ключові властивості: 1) ядерний метод для запобігання недонавчання (underfitting); 2) принцип розрідженості та 3) принцип великої грані (large margin) для запобігання перенавчання.

### 11. Дерева класифікації та регресії. Особливості, обмеження та переваги.

$𝑓(𝐱)=𝔼[𝑦|𝐱]=∑_{𝑚=1}^{𝑀}𝑤_𝑚 𝕀(𝐱∈ℛ_𝑚 ) =∑_{𝑚=1}^{𝑀}(w_𝑚 𝜙(𝐱, 𝐯_𝑚 ))$  де $R_m$ - m-й регіон

Переваги: 
- інтерпретовані
- можуть поєднувати дискретні та неперервні значення
- нечутливі для монотонної трансформації входу
- автоматично проводять відбір змінних
- відносно нечутливі до викидів
- можуть сприймати пропущені данні

Недоліки:
- не дуже точно передбачують результат
- нестабільні (маленька зміна вхідних даних может вплинути на структуру дерева)

### 12. Поняття подільних ядерних функцій. Вимоги до функцій.
  $\phi(x1, ..., xn) = \phi(x1) * ... * \phi(xn)\$
  
### 13. Ансамблеві класифікатори. Особливості та приклади.

Ансамблеві класифікатори
Моделі що агругують комбінації ваг більш простих моделей f(y|x, $\theta$) = $\sum$ $weights_i * f_m(y|x)$, де ваги - тренований параметри. Прикладом ансамблевих методів є
Random Forest
Бустингові дерева
Також підвидом ансамблевих моделей можна виділити Stacking, де ми поєднуємо передбачення більш простих моделей для тренування більш складних.

### 14. Методи агрегації даних (bagging) при налаштуванні класифікаторів.
* bootstrap aggregating (bagging) is a technique to reduce the variance of an estimate to average together many estimates. For example, we can train 𝑀 different trees on different subsets of the data, chosen randomly with replacement, and then compute the ensemble f(x) = sum(f_m(x))/M

### 15. Ансамлеві методи підсилення (boosting) класифікаторів.

Бустингові класифікатори - жадібні алгоритми, які поєднують в собі більш прості модели за $f(x) = w_0 + sum(w_m * \phi_m(x)) $ де кожний $\phi_m$ базовий алгоритм навчання. В залежності від функції втрати існую різні типи бустингових класифікаторів (L2Boosting, Gradient Boosting, AdaBosting, LogitBoosting)
![image.png](attachment:image.png)![image.png](attachment:image.png)![image.png](attachment:image.png)![image.png](attachment:image.png)![image.png](attachment:image.png)

### DONE 1. Задано послідовність вихідних станів марківської моделі:
  X = {1, 3, 2, 6, 10, 1, 4, 3, 7, 9, 9}
  Загальна кількість станів моделі рівна 10. Розрахувати матрицю переходів (transition matrix) на 4 ітерації.


In [2]:
x = np.array([1, 3, 2, 6, 10, 1, 4, 3, 7, 9, 9])
x

array([ 1,  3,  2,  6, 10,  1,  4,  3,  7,  9,  9])

In [3]:
def matrix_filled(x):
    matrix = np.zeros((10, 10))
    for i in range(x.shape[0] - 1):
        val_1 = x[i]
        val_2 = x[i+1]
        matrix[val_2 - 1][val_1 - 1] += 1
        #print(val_1, val_2)
    return matrix

In [4]:
def normalize_matrix(matrix, epsilon=1e-10):
    row_sums = (matrix + epsilon).sum(axis = 1)
    res = matrix / row_sums[:, np.newaxis]
    return res

In [5]:
matrix = matrix_filled(x)
matrix_norm = normalize_matrix(matrix)
print('Normalized matrix')
print(matrix_norm)
print('Matrix in power of 4')
print(np.linalg.matrix_power(matrix_norm, 4))

Normalized matrix
[[0.  0.  0.  0.  0.  0.  0.  0.  0.  1. ]
 [0.  0.  1.  0.  0.  0.  0.  0.  0.  0. ]
 [0.5 0.  0.  0.5 0.  0.  0.  0.  0.  0. ]
 [1.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  1.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  1.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.5 0.  0.5 0. ]
 [0.  0.  0.  0.  0.  1.  0.  0.  0.  0. ]]
Matrix in power of 4
[[0.     0.     1.     0.     0.     0.     0.     0.     0.     0.    ]
 [0.     0.     0.     0.     0.     0.5    0.     0.     0.     0.5   ]
 [0.     0.5    0.     0.     0.     0.5    0.     0.     0.     0.    ]
 [0.     1.     0.     0.     0.     0.     0.     0.     0.     0.    ]
 [0.     0.     0.     0.     0.     0.     0.     0.     0.     0.    ]
 [0.5    0.     0.     0.     0.     0.     0.     0.     0.     0.5   ]
 [0.     0.     0.     0.     0.     0.5    0.     0.     0.     0.5   ]
 [0.     0.     0. 

2. Задано послідовність станів марківської моделі:
  X = {2,5,4,7,3,4,2,3,5,4,6,7,7,6,1}
  pi = {0.3; 0.1; 0.1; 0.2; 0.1; 0.1; 0.1}
  Загальна кількість станів рівна 7. Розрахувати значення елементів вектора стану pi на 3 ітерації.

In [6]:
X,pi,n = np.array([2,5,4,7,3,4,2,3,5,4,6,7,7,6,1]),np.array([0.3, 0.1, 0.1, 0.2, 0.1, 0.1, 0.1]),7

n_states = 7
n_iterations = 3

matrix = matrix_filled(x, n_states)
matrix_norm = normalize_matrix(matrix)
matrix_norm2 = np.linalg.matrix_power(matrix_norm, n_iterations)
pi2 = np.dot(pi,matrix_norm)
pi3 = np.dot(pi2,matrix_norm2)
print(pi3)

### 3. Задано емпіричні розподіли трьох класів:
  X1 = {(1, 3); (2, 4); (3, 5)}
  X2 = {(2, 5); (0, 8); (4, 1); (1, 1)}
  X3 = {(1, 1); (-5 , 4); (0, 8)}

Використовуючи GMM вирішити задачу багатокласової класифікації для нового елемента x = (2, 7)


In [7]:
from scipy.stats import multivariate_normal, norm

In [8]:
x1 = np.array([[1, 3], [2, 4], [3, 5]])
x2 = np.array([[2, 5], [0, 8], [4, 1],[1, 1]])
x3 = np.array([[1, 1], [-5 , 4], [0, 8]])

x_new = np.array([2, 7])

In [9]:
mean_1 = np.mean(x1, axis=0, keepdims=True)
mean_2 = np.mean(x2, axis=0, keepdims=True)
mean_3 = np.mean(x3, axis=0, keepdims=True)

cov_1 = np.cov(x1)
cov_2 = np.cov(x2)
cov_3 = np.cov(x3)

In [10]:
print('== model1 ==')
print('Mean: ', mean_1,'\nCov: ', cov_1)
print('== model2 ==')
print('Mean: ', mean_2,'\nCov: ', cov_2)
print('== model3 ==')
print('Mean: ', mean_3,'\nCov: ', cov_3)

== model1 ==
Mean:  [[2. 4.]] 
Cov:  [[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]
== model2 ==
Mean:  [[1.75 3.75]] 
Cov:  [[  4.5  12.   -4.5   0. ]
 [ 12.   32.  -12.    0. ]
 [ -4.5 -12.    4.5   0. ]
 [  0.    0.    0.    0. ]]
== model3 ==
Mean:  [[-1.33333333  4.33333333]] 
Cov:  [[ 0.   0.   0. ]
 [ 0.  40.5 36. ]
 [ 0.  36.  32. ]]


In [11]:
mean_1

array([[2., 4.]])

### DONE 4. Обчислити перші 2 головні компоненти для заданої вибірки значень: [Залишити 2 головні компоненти (перші 2 рядки) в s, перемножити на інші]
  X = {(1,2,3);
     (2,3,4);
     (7,7,9);
     (0, 11, 0)}


In [46]:
n=2
X = np.array([[1,2,3],
              [2,3,4],
              [7,7,9],
              [0,11,0]])
U,s,V=np.linalg.svd(X)

U,s,V

(array([[-0.21299335,  0.11166707,  0.7341609 ,  0.63495832],
        [-0.31466555,  0.15717558,  0.5437956 , -0.76194998],
        [-0.7774661 ,  0.46334971, -0.40586529,  0.12699166],
        [-0.50116454, -0.86494702, -0.02382178,  0.0115447 ]]),
 array([16.44752767,  8.42106835,  1.25077632]),
 array([[-0.3820992 , -0.74935615, -0.54080086],
        [ 0.4357483 , -0.66216163,  0.60964366],
        [-0.8149378 , -0.0027087 ,  0.57954209]]))

In [51]:
def reconstruct(U,s,V,n=2):
    s[n:]=0
    S = np.zeros((U.shape[0],V.shape[0]))
    S[:s.shape[0],:s.shape[0]]=np.diag(s)
    return U@S@V

In [52]:
reconstruct(U,s,V,n=2)

array([[ 1.74833381,  2.00248732,  2.46782326],
       [ 2.55429353,  3.00184237,  3.60581479],
       [ 6.58629952,  6.99862494,  9.29420263],
       [-0.02428166, 10.99991929,  0.01726787]])

### DONE 5. Визначити вектор прихованих факторів (latent variables) 
за відомою матрицею змішування W та вектором математичного очікування mu. Розглянути випадок, коли вплив помилок відсутній (eps -> 0)
  mu = (1, 3, 5, 7)
  W = (1, 2, 3, 7, 11)
    (3,7,2,3,4)
    (9,4,0,0,1)
    (1,1,1,1,1)


In [123]:
mu = np.array([1, 3, 5, 7])
W = np.array([[1, 2, 3, 7, 11],
              [3, 7, 2, 3, 4],
              [9, 4, 0, 0, 1],
              [1, 1, 1, 1, 1]])
# W*z + mu = epsilon -> 0
# WZ = -mu
# z = W^(-1) * (-mu)
np.set_printoptions(suppress=True)
z = np.dot(np.linalg.pinv(W),(-mu))
print(z)

[-1.67  1.62 -7.95 -2.56  3.57]


### DONE 6. Вирішити систему лінійних арифметичних рівнянь:
  (1) x1 + 4x2 + x3 = 0
  (2) 8x2 - 3x3 = 5
  (3) x1 + 78x3 = 21
  (4) 3x1 + 2x2 = 4
  (5) 6x1+x2+x3 = 77


In [16]:
from sklearn.linear_model import LinearRegression

X = np.array([[1,4,1],
              [0,8,-3],
              [1,0,78],
              [3,2,0],
              [6,1,1]
             ])
y = np.array([0,5,21,4,77])


lr = LinearRegression().fit(X,y)
lr.coef_

array([23.2248782 , 11.04936545,  0.97260676])

7. Вирішити задачу багатокласової класифікації для виміру x={1, 2.5, 7} при відомих густинах розподілу класів (модель GMM):
  C1 = {(1, 4, 7), (2, 8, 9)}
  C2 = {(1, 1, 0), (8, 10, 28)}
  C3 = {(0, 7, 11), (7, 5, 15)}

In [54]:
def calc_cov_vect(X):
    Y = X-X.mean(axis=1,keepdims=True)
    matr = np.zeros(X.shape)
    for i in range(Y.shape[0]):
        col = np.array(Y[:,i],ndmin=2)
        rm = np.dot(col.T,col)
        matr+=rm   
    return matr/X.shape[0]

In [17]:
x1 = np.array([[1, 4, 7], [2, 8, 9]])
x2 = np.array([[1, 1, 0], [8, 10, 28]])
x3 = np.array([[0, 7, 11], [7, 5, 15]])

x_new = np.array([1, 2.5, 7])

mean_1 = np.mean(x1, axis=0, keepdims=True)
mean_2 = np.mean(x2, axis=0, keepdims=True)
mean_3 = np.mean(x3, axis=0, keepdims=True)

cov_1 = np.cov(x1)
cov_2 = np.cov(x2)
cov_3 = np.cov(x3)

In [53]:
x1

array([[1, 4, 7],
       [2, 8, 9]])

In [55]:
calc_cov_vect(x1)

ValueError: operands could not be broadcast together with shapes (2,3) (2,2) (2,3) 

In [18]:
print('== model1 ==')
print('Mean: ', mean_1,'\nCov: ', cov_1)
print('== model2 ==')
print('Mean: ', mean_2,'\nCov: ', cov_2)
print('== model3 ==')
print('Mean: ', mean_3,'\nCov: ', cov_3)

== model1 ==
Mean:  [[1.5 6.  8. ]] 
Cov:  [[ 9.         10.5       ]
 [10.5        14.33333333]]
== model2 ==
Mean:  [[ 4.5  5.5 14. ]] 
Cov:  [[  0.33333333  -6.33333333]
 [ -6.33333333 121.33333333]]
== model3 ==
Mean:  [[ 3.5  6.  13. ]] 
Cov:  [[31. 19.]
 [19. 28.]]


In [19]:
mean_1[0]

array([1.5, 6. , 8. ])

In [20]:
cov_1

array([[ 9.        , 10.5       ],
       [10.5       , 14.33333333]])

In [21]:
stats.multivariate_normal(mean_1[0], cov_1).pdf(x_new)

ValueError: Dimension mismatch: array 'cov' is of shape (2, 2), but 'mean' is a vector of length 3.

### DONE 8. Задано послідовність станів марківської моделі першого порядку:
  X = {1, 7, 5, 4, 3, 10, 1, 1, 5, 7, 5, 6, 1}
  Загальна кількість станів моделі рівна 10. Розрахувати матрицю переходів (transition matrix) на 3 ітерації.


In [22]:
X,n = np.array([1, 7, 5, 4, 3, 10, 1, 1, 5, 7, 5, 6, 1]),10

In [39]:
x = matrix_filled(X)
normalized_x = normalize_matrix(x)
np.linalg.matrix_power(normalized_x,3)

array([[0. , 0. , 0. , 0.5, 0. , 0. , 0.5, 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0.5],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 1. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0.5, 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0.5],
       [0. , 0. , 0. , 0. , 0. , 1. , 0. , 0. , 0. , 0. ]])

### DONE 9. Обчислити матрицю Грама для ядерної функції k(x) = xsin(x) + x^2 / 5 
на множині X = {1, 0, 7, 6, 4, 10}. Аргумент функції sin(x) задано в радіанах.


In [129]:
def kernel(x):
    return x * np.sin(x) + (x ** 2) / 5

X = np.array([1,0,7,6,4,10])

In [128]:
def form_gram_matrix(X,kernel):
    n = X.shape[0]
    K = np.array([[kernel(X[i])*kernel(X[j]) for i in range(n)] for j in range(n)])
    return K
form_gram_matrix(X,kernel)

array([[  1.08,   0.  ,  15.  ,   5.75,   0.18,  15.16],
       [  0.  ,   0.  ,   0.  ,   0.  ,   0.  ,   0.  ],
       [ 15.  ,   0.  , 207.33,  79.53,   2.49, 209.65],
       [  5.75,   0.  ,  79.53,  30.51,   0.95,  80.42],
       [  0.18,   0.  ,   2.49,   0.95,   0.03,   2.52],
       [ 15.16,   0.  , 209.65,  80.42,   2.52, 211.99]])

### Done 10. Перевірити, чи є відносить задана ядерна функція k(x) = exp{sin(x) + 1} + xtan(x) до класу ядерних функцій Мерсена. 
Перевірку виконати на множині X={7, 6, 2, 1, 0, 4, 6, 9}. Аргументи тригонометричних функцій задано в радіанах.

Маємо сформувати матрицю грама та перевірити, що вона positive definite. Якщо вона буде вона positive definite, ядерна ф-ція відноситься до класу ядерних ф-й Мерсена

In [113]:
X = np.array([7,6,2,1,0,4,6,9])
def k(x):
    return np.exp(np.sin(x)+1) + x*np.tan(x)

def form_gram_matrix(X,kernel):
    n = X.shape[0]
    K = np.array([[kernel(X[i])*kernel(X[j]) for i in range(n)] for j in range(n)])
    return K

def check_positive_definite(K,X):
    return X.T@K@X 

def check_kernel_function(X,kernel,print_gram=False):
    K = form_gram_matrix(X,kernel)
    
    if print_gram:
        print(f'Gram matrix:\n{K}')
    
    prod = check_positive_definite(K,X)
    print(f'X.T@K@X={prod}')
    if prod>0:
        return "kernel function is positive-definite"
    return "kernel function isn't positive-definite"

In [116]:
check_kernel_function(X,k,print_gram=True)

Gram matrix:
[[128.68   3.51  26.98  89.2   30.84  67.     3.51   0.38]
 [  3.51   0.1    0.74   2.43   0.84   1.83   0.1    0.01]
 [ 26.98   0.74   5.66  18.7    6.46  14.05   0.74   0.08]
 [ 89.2    2.43  18.7   61.83  21.37  46.44   2.43   0.27]
 [ 30.84   0.84   6.46  21.37   7.39  16.06   0.84   0.09]
 [ 67.     1.83  14.05  46.44  16.06  34.89   1.83   0.2 ]
 [  3.51   0.1    0.74   2.43   0.84   1.83   0.1    0.01]
 [  0.38   0.01   0.08   0.27   0.09   0.2    0.01   0.  ]]
X.T@K@X=14321.124233689508


'kernel function is positive-definite'

### Done 11. Перевірити, чи належить задана ядерна функція k(x) = ln(1 + exp(-x) + tg(x)^2) до класу ядерних функцій Мерсена. 
  Перевірку виконати на множині X={1,9,7,5,3,2}. Аргументи тригонометричних функцій задано в радіанах.


In [119]:
X = np.array([1,9,7,5,3,2])
def k(x):
    return np.log(1+np.exp(-x)+np.tan(x)**2)

In [120]:
check_kernel_function(X,k,print_gram=True)

Gram matrix:
[[1.78 0.25 0.75 3.36 0.09 2.37]
 [0.25 0.03 0.11 0.47 0.01 0.33]
 [0.75 0.11 0.32 1.43 0.04 1.  ]
 [3.36 0.47 1.43 6.35 0.17 4.48]
 [0.09 0.01 0.04 0.17 0.   0.12]
 [2.37 0.33 1.   4.48 0.12 3.16]]
X.T@K@X=544.14218243972


'kernel function is positive-definite'

### Done 12. Визначити вектор прихованих факторів (latent variables) за відомою матрицею змішування W та вектором математичного очікування mu. 
  Розглянути випадок, коли вплив помилок відсутній (eps -> 0)
  mu = (4,5,3,6)
  W = (1,2,3)
    (95,7,0)
    (1,2,5)
    (0,0,1)


In [130]:
W =np.array([[1,2,3],
    [95,7,0],
    [1,2,5],
    [0,0,1]])
mu = np.array([4,5,3,6])
z = np.dot(np.linalg.pinv(W),(-mu))
print(z)

[-0.18  1.67 -1.67]


### DONE 13. Обчислити перші 3 головні компоненти для заданої вибірки значень:
  X = {(1,2,3,8);
     (5,3,6,2);
     (7,5,6,8);
     (0,0,0,1)}


In [25]:
X = np.array([[1,2,3,8],
     [5,3,6,2],
     [7,5,6,8],
     [0,0,0,1]])

n_components = 3

u, s, vh = np.linalg.svd(X, full_matrices=True)

In [26]:
u

array([[-0.45103945,  0.74955999,  0.47409566, -0.09978246],
       [-0.45211097, -0.64452157,  0.60908097,  0.09595827],
       [-0.76864884, -0.06716484, -0.63454343, -0.04497204],
       [-0.03657932,  0.13505797, -0.04010375,  0.98934978]])

In [27]:
s[n_components:] = 0
np.diag(s)

array([[17.10171748,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  5.64592816,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  1.62212023,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ]])

In [28]:
vh

array([[-0.47317681, -0.35678615, -0.50741554, -0.62556919],
       [-0.52129636, -0.13642911, -0.35803476,  0.76252759],
       [-0.56857901, -0.24491583,  0.78262522, -0.0650531 ],
       [ 0.42552523, -0.8911268 ,  0.04287594,  0.15160132]])

In [29]:
reconst = np.matrix(u) * np.diag(s) * np.matrix(vh)
reconst

matrix([[ 1.00650628,  1.98637468,  3.00065557,  8.00231798],
        [ 4.99374308,  3.01310313,  5.99936955,  1.99777085],
        [ 7.00293239,  4.99385906,  6.00029547,  8.00104472],
        [-0.06451019,  0.135096  , -0.00650005,  0.97701704]])

14. Обчислити антиградіент квадратичної функції втрат в точці x = 0, y = 1:
  loss = 1/2 * (y - f(x)) ^2
  f(x) = tg(x^2 - 2) + exp(sin(x))

In [33]:
def f(x):
    return np.tan(x**2-2)+np.exp(np.sin(x))

def loss(x,y):
    return 0.5*(y-f(x)) **2

x,y=0,1

### Done 15. Вирішити систему лінійних арифметичних рівнянь:
    *  2x1 - 2x2 + 8x3 + 12x4 = 0
    *  22x2 + 43x4 = 1
    *  -3x1 + 7x2 = 4
    *  5x2 + 4x4 = 3
    *  11x1+12x2-4x3 = 101

In [121]:
X = np.array([[2, -2, 8, 12],
              [0, 22 ,0, 43],
              [-3, 7 ,0, 0],
              [0, 5, 0, 4],
              [11, 12, -4, 0]])

y = np.array([0, 1, 4, 3, 101])

# theta = (X.T * X)^(-1)* X.T * y
X = np.matrix(X)
theta = np.dot(np.linalg.inv(X.T * X) * X.T, y)
print(theta)

[[ 6.36  3.02  1.43 -1.53]]


### 

### Деякі задачі протягом триму:

#1. До якого з розподілів належать нові дані?

In [24]:
x_new = 1.75

In [23]:
p1,p2,p3,p4 = stats.norm.pdf(1.75,0,1),stats.norm.pdf(1.75,3,1.5),stats.norm.pdf(1.75,1.5,2),stats.laplace.pdf(1.75,2,2)
probs = [p1,p2,p3,p4]
max(probs), probs.index(max(probs))

(0.22062422564614886, 3)

#2. Знайти параметри розподілу (MVN)

In [7]:
x1 = np.array([1,2,1,3,7])
x2 = np.array([2,1,2,4,9])

In [25]:
mean_vector = np.array([x1.mean(),x2.mean()])

$$ \frac{\sum(x_i-m)(x_i-m)^T}{N} $$

In [26]:
cov_matrix  = np.cov(x1,x2)

Множимо матриці

In [49]:
np.set_printoptions(precision=5)

#Знайти параметри розподілів: вектор середнього та матрицію коваріації

In [165]:
def calc_cov_vect(X):
    Y = X-X.mean(axis=1,keepdims=True)
    matr = np.zeros(X.shape)
    for i in range(Y.shape[0]):
        col = np.array(Y[:,i],ndmin=2)
        rm = np.dot(col.T,col)
        matr+=rm   
    return matr/X.shape[0]

In [176]:
calc_cov_vect(X)

array([[0.22222222, 0.22222222, 0.33333333],
       [0.22222222, 0.22222222, 0.33333333],
       [0.33333333, 0.33333333, 0.66666667]])

In [1]:
from sklearn.decomposition import PCA

In [6]:
X = np.array([[1,2,3],
     [2,3,4],
     [7,7,9],
     [0, 11, 0]])

In [7]:
X

array([[ 1,  2,  3],
       [ 2,  3,  4],
       [ 7,  7,  9],
       [ 0, 11,  0]])

In [38]:
def kernel(x):
    return x*np.sin(x)+(x**2)/5

X = ([1,0,7,6,4,10])

for i in range(6):
    for j in range(6):
        arr[i,j]=kernel(X[i])*kernel(X[j])

arr

array([[  1.08466181,   0.        ,  14.99604301,   5.75257229,
          0.17995579,  15.16359768],
       [  0.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ],
       [ 14.99604301,   0.        , 207.3284995 ,  79.53245929,
          2.48798727, 209.6450344 ],
       [  5.75257229,   0.        ,  79.53245929,  30.5091297 ,
          0.95440688,  80.42109602],
       [  0.17995579,   0.        ,   2.48798727,   0.95440688,
          0.02985639,   2.5157862 ],
       [ 15.16359768,   0.        , 209.6450344 ,  80.42109602,
          2.5157862 , 211.98745255]])

In [18]:
pairwise_distances(X,)

array([[ 1,  0,  7,  6,  4, 10]])

In [22]:
from sklearn.metrics.pairwise import pairwise_distances
gram = pairwise_distances(X,metric)

In [23]:
gram

array([[0.]])

In [2]:
def f(x):
    return np.tan(x**2-2)+np.exp(np.sin(x))

In [5]:
(1-f(0))*2

-4.370079726523038

In [ ]:
tg(x^2 - 2) + exp(sin(x))