In [2]:
import numpy as np
from scipy import stats

1. Класичний та імовірнисний методи головних компонент. Методи отримання головних компонентів.
<br>< -- insert ans here

2. Метод незалежних компонент. Критерії незалежності компонентів.
<br>< -- insert ans here

3. Застосування марківських моделей в задачах моделювання природних мов.
4. Умови існування стаціонарного розподілу для марківських моделей.
5. Методи прийняття рішень (inference) з використанням прихованих марківських моделей.
6. Робастна та гребнева (ridge) регресія. Порівняння з лінійною регресією.
7. Виведення основного рівняння лінійної регресії.
8. Поняття ядерних функцій. Вимоги до ядерних функцій (теорема Мерсера).
9. Відмінності лінійної та логістичної регресії з точки зору вирішеня задачі класифікації.
10. Метод опорних векторів (Support Vector Machine, SVM). Відмінності від інших методів класифікації даних.
11. Дерева класифікації та регресії. Особливості, обмеження та переваги.
12. Поняття подільних ядерних функцій. Вимоги до функцій.
  \phi(x1, ..., xn) = \phi(x1) * ... * \phi(xn)
13. Ансамблеві класифікатори. Особливості та приклади.
14. Методи агрегації даних (bagging) при налаштуванні класифікаторів.
15. Ансамлеві методи підсилення (boosting) класифікаторів.

1. Задано послідовність вихідних станів марківської моделі:
  X = {1, 3, 2, 6, 10, 1, 4, 3, 7, 9, 9}
  Загальна кількість станів моделі рівна 10. Розрахувати матрицю переходів (transition matrix) на 4 ітерації.


2. Задано послідовність станів марківської моделі:
  X = {2,5,4,7,3,4,2,3,5,4,6,7,7,6,1}
  pi = {0.3; 0.1; 0.1; 0.2; 0.1; 0.1; 0.1}
  Загальна кількість станів рівна 7. Розрахувати значення елементів вектора стану pi на 3 ітерації.

3. Задано емпіричні розподіли трьох класів:
  X1 = {(1, 3); (2, 4); (3, 5)}
  X2 = {(2, 5); (0, 8); (4, 1); (1, 1)}
  X3 = {(1, 1); (-5 , 4); (0, 8)}

Використовуючи GMM вирішити задачу багатокласової класифікації для нового елемента x = (2, 7)


4. Обчислити перші 2 головні компоненти для заданої вибірки значень:
  X = {(1,2,3);
     (2,3,4);
     (7,7,9);
     (0, 11, 0)}


5. Визначити вектор прихованих факторів (latent variables) за відомою матрицею змішування W та вектором математичного очікування mu. Розглянути випадок, коли вплив помилок відсутній (eps -> 0)
  mu = (1, 3, 5, 7)
  W = (1, 2, 3, 7, 11)
    (3,7,2,3,4)
    (9,4,0,0,1)
    (1,1,1,1,1)


6. Вирішити систему лінійних арифметичних рівнянь:
  (1) x1 + 4x2 + x3 = 0
  (2) 8x2 - 3x3 = 5
  (3) x1 + 78x3 = 21
  (4) 3x1 + 2x2 = 4
  (5) 6x1+x2+x3 = 77


7. Вирішити задачу багатокласової класифікації для виміру x={1, 2.5, 7} при відомих густинах розподілу класів (модель GMM):
  C1 = {(1, 4, 7), (2, 8, 9)}
  C2 = {(1, 1, 0), (8, 10, 28)}
  C3 = {(0, 7, 11), (7, 5, 15)}

8. Задано послідовність станів марківської моделі першого порядку:
  X = {1, 7, 5, 4, 3, 10, 1, 1, 5, 7, 5, 6, 1}
  Загальна кількість станів моделі рівна 10. Розрахувати матрицю переходів (transition matrix) на 3 ітерації.


9. Обчислити матрицю Грама для ядерної функції k(x) = xsin(x) + x^2 / 5 на множині X = {1, 0, 7, 6, 4, 10}. Аргумент функції sin(x) задано в радіанах.


10. Перевірити, чи є відносить задана ядерна функція k(x) = exp{sin(x) + 1} + xtan(x) до класу ядерних функцій Мерсена. Перевірку виконати на множині X={7, 6, 2, 1, 0, 4, 6, 9}. Аргументи тригонометричних функцій задано в радіанах.


11. Перевірити, чи належить задана ядерна функція k(x) = ln(1 + exp(-x) + tg(x)^2) до класу ядерних функцій Мерсена. 
  Перевірку виконати на множині X={1,9,7,5,3,2}. Аргументи тригонометричних функцій задано в радіанах.


12. Визначити вектор прихованих факторів (latent variables) за відомою матрицею змішування W та вектором математичного очікування mu. 
  Розглянути випадок, коли вплив помилок відсутній (eps -> 0)
  mu = (4,5,3,6)
  W = (1,2,3)
    (95,7,0)
    (1,2,5)
    (0,0,1)


13. Обчислити перші 3 головні компоненти для заданої вибірки значень:
  X = {(1,2,3,8);
     (5,3,6,2);
     (7,5,6,8);
     (0,0,0,1)}


14. Обчислити антиградіент квадратичної функції втрат в точці x = 0, y = 1:
  loss = 1/2 * (y - f(x)) ^2
  f(x) = tg(x^2 - 2) + exp(sin(x))

15. Вирішити систему лінійних арифметичних рівнянь:

    *  2x1 - 2x2 + 8x3 + 12x4 = 0
    *  22x2 + 43x4 = 1
    *  -3x1 + 7x2 = 4
    *  5x2 + 4x4 = 3
    *  11x1+12x2-4x3 = 101

In [88]:
from sklearn.linear_model import LinearRegression

X = np.array([[2,-2,8,12],
                [0,22,0,43],
                [-3,7,0,0],
                [0,5,0,4],
                [11,12,-4,0]])
y = np.array([0,1,4,3,101])

lr = LinearRegression().fit(X,y)
lr.coef_

array([ 6.46796206,  5.39555864,  5.13231552, -2.40319223])

### Деякі задачі протягом триму:

#1. До якого з розподілів належать нові дані?

In [24]:
x_new = 1.75

In [23]:
p1,p2,p3,p4 = stats.norm.pdf(1.75,0,1),stats.norm.pdf(1.75,3,1.5),stats.norm.pdf(1.75,1.5,2),stats.laplace.pdf(1.75,2,2)
probs = [p1,p2,p3,p4]
max(probs), probs.index(max(probs))

(0.22062422564614886, 3)

#2. Знайти параметри розподілу (MVN)

In [7]:
x1 = np.array([1,2,1,3,7])
x2 = np.array([2,1,2,4,9])

In [25]:
mean_vector = np.array([x1.mean(),x2.mean()])

$$ \frac{\sum(x_i-m)(x_i-m)^T}{N} $$

In [26]:
cov_matrix  = np.cov(x1,x2)

Множимо матриці

In [49]:
np.set_printoptions(precision=5)

#Знайти параметри розподілів: вектор середнього та матрицію коваріації

In [165]:
def calc_cov_vect(X):
    Y = X-X.mean(axis=1,keepdims=True)
    matr = np.zeros(X.shape)
    for i in range(Y.shape[0]):
        col = np.array(Y[:,i],ndmin=2)
        rm = np.dot(col.T,col)
        matr+=rm   
    return matr/X.shape[0]

In [176]:
calc_cov_vect(X)

array([[0.22222222, 0.22222222, 0.33333333],
       [0.22222222, 0.22222222, 0.33333333],
       [0.33333333, 0.33333333, 0.66666667]])

In [1]:
from sklearn.decomposition import PCA

In [6]:
X = np.array([[1,2,3],
     [2,3,4],
     [7,7,9],
     [0, 11, 0]])

In [7]:
X

array([[ 1,  2,  3],
       [ 2,  3,  4],
       [ 7,  7,  9],
       [ 0, 11,  0]])

In [38]:
def kernel(x):
    return x*np.sin(x)+(x**2)/5

X = ([1,0,7,6,4,10])

for i in range(6):
    for j in range(6):
        arr[i,j]=kernel(X[i])*kernel(X[j])

arr

array([[  1.08466181,   0.        ,  14.99604301,   5.75257229,
          0.17995579,  15.16359768],
       [  0.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ],
       [ 14.99604301,   0.        , 207.3284995 ,  79.53245929,
          2.48798727, 209.6450344 ],
       [  5.75257229,   0.        ,  79.53245929,  30.5091297 ,
          0.95440688,  80.42109602],
       [  0.17995579,   0.        ,   2.48798727,   0.95440688,
          0.02985639,   2.5157862 ],
       [ 15.16359768,   0.        , 209.6450344 ,  80.42109602,
          2.5157862 , 211.98745255]])

In [18]:
pairwise_distances(X,)

array([[ 1,  0,  7,  6,  4, 10]])

In [22]:
from sklearn.metrics.pairwise import pairwise_distances
gram = pairwise_distances(X,metric)

In [23]:
gram

array([[0.]])

In [2]:
def f(x):
    return np.tan(x**2-2)+np.exp(np.sin(x))

In [5]:
(1-f(0))*2

-4.370079726523038

In [ ]:
tg(x^2 - 2) + exp(sin(x))