In [1]:
import numpy as np
from scipy import stats

#1. До якого з розподілів належать нові дані?

In [24]:
x_new = 1.75

In [23]:
p1,p2,p3,p4 = stats.norm.pdf(1.75,0,1),stats.norm.pdf(1.75,3,1.5),stats.norm.pdf(1.75,1.5,2),stats.laplace.pdf(1.75,2,2)
probs = [p1,p2,p3,p4]
max(probs), probs.index(max(probs))

(0.22062422564614886, 3)

#2. Знайти параметри розподілу (MVN)

In [7]:
x1 = np.array([1,2,1,3,7])
x2 = np.array([2,1,2,4,9])

In [25]:
mean_vector = np.array([x1.mean(),x2.mean()])

$$ \frac{\sum(x_i-m)(x_i-m)^T}{N} $$

In [26]:
cov_matrix  = np.cov(x1,x2)

Множимо матриці

In [49]:
np.set_printoptions(precision=5)

#Знайти параметри розподілів: вектор середнього та матрицію коваріації

In [165]:
def calc_cov_vect(X):
    Y = X-X.mean(axis=1,keepdims=True)
    matr = np.zeros(X.shape)
    for i in range(Y.shape[0]):
        col = np.array(Y[:,i],ndmin=2)
        rm = np.dot(col.T,col)
        matr+=rm   
    return matr/X.shape[0]

In [176]:
calc_cov_vect(X)

array([[0.22222222, 0.22222222, 0.33333333],
       [0.22222222, 0.22222222, 0.33333333],
       [0.33333333, 0.33333333, 0.66666667]])

In [4]:
import numpy as np

In [1]:
from sklearn.decomposition import PCA

In [6]:
X = np.array([[1,2,3],
     [2,3,4],
     [7,7,9],
     [0, 11, 0]])

In [7]:
X

array([[ 1,  2,  3],
       [ 2,  3,  4],
       [ 7,  7,  9],
       [ 0, 11,  0]])

In [38]:
def kernel(x):
    return x*np.sin(x)+(x**2)/5

X = ([1,0,7,6,4,10])

for i in range(6):
    for j in range(6):
        arr[i,j]=kernel(X[i])*kernel(X[j])

arr

array([[  1.08466181,   0.        ,  14.99604301,   5.75257229,
          0.17995579,  15.16359768],
       [  0.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ],
       [ 14.99604301,   0.        , 207.3284995 ,  79.53245929,
          2.48798727, 209.6450344 ],
       [  5.75257229,   0.        ,  79.53245929,  30.5091297 ,
          0.95440688,  80.42109602],
       [  0.17995579,   0.        ,   2.48798727,   0.95440688,
          0.02985639,   2.5157862 ],
       [ 15.16359768,   0.        , 209.6450344 ,  80.42109602,
          2.5157862 , 211.98745255]])

In [18]:
pairwise_distances(X,)

array([[ 1,  0,  7,  6,  4, 10]])

In [22]:
from sklearn.metrics.pairwise import pairwise_distances
gram = pairwise_distances(X,metric)

In [23]:
gram

array([[0.]])